package com.sebaixia.business.entities;

public enum OptionEnum {
	SB_PLAN_WIDTH,
	SB_PLAN_HEIGHT,
	SB_L_LEFT_WIDTH,
	SB_L_LEFT_HEIGHT,
	SB_L_BOTTOM_WIDTH,
	SB_L_BOTTOM_HEIGHT,
	SB_U_LEFT_WIDTH,
	SB_U_LEFT_HEIGHT,
	SB_U_BOTTOM_WIDTH,
	SB_U_BOTTOM_HEIGHT,
	SB_U_RIGHT_WIDTH,
	SB_U_RIGHT_HEIGHT,
}
